apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: sovtech
  region: us-east-2

vpc:
  clusterEndpoints:
    publicAccess: true
    privateAccess: true

nodeGroups:
  - name: ng-1
    instanceType: t2.micro
    desiredCapacity: 1
    volumeSize: 10
