apiVersion: v1
kind: Service
metadata:
  name: gosovtech-service
spec:
  type: LoadBalancer
  selector:
    name: gosovtech-pod
    app: go-graphql-sovtech
  ports:
    - port: 80
      targetPort: 8081
      nodePort: 30004
